site_name: AMI - Archivio del Maoismo Italiano
site_description: Catalogo digitale per la ricerca storica sul maoismo in Italia
site_author: Ivan Masci
site_url: https://ami-aim.github.io/archivio-maoismo-italiano/

theme:
  name: material
  language: it
  features:
    - header.autohide
    - navigation.top
    - search.suggest
    - search.highlight
    # - navigation.tabs          ← COMMENTATO (non serve più)
  palette:
    - scheme: default
      primary: custom
      accent: red
  logo: immagini/logo.png
  favicon: immagini/favicon.png

extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

nav:
  - Home: index.md
  - Il progetto: progetto.md
  - Archivio: documenti/
  - Persone: persone/
  - Organizzazioni: organizzazioni/

extra:
  homepage: /archivio-maoismo-italiano/